(function () {
  'use strict';

  var content = {
    sections: [
      {
        id: 'getting-started',
        title: 'Getting Started',
        blurb: 'Learn what ClippingHub is and load your first stream.',
        steps: [
          {
            id: 'welcome',
            title: 'Welcome to ClippingHub',
            body: 'ClippingHub clips live streams and uploads from Rumble.<br><br>This quick walkthrough uses a real channel so you can follow along.',
            placement: 'center',
            advance: { type: 'next-button' },
          },
          {
            id: 'rumble-browser',
            title: 'The Rumble browser',
            body: 'This big page is an embedded Rumble browser. Find streams and videos here, then send the URL to the player.',
            target: '#channelBrowser',
            placement: 'center',
            advance: { type: 'next-button' },
          },
          {
            id: 'navigate-channel',
            title: 'Navigating to a channel',
            body: 'We will load the <b>nickjfuentes</b> channel as a demo. Click <b>Next</b> to navigate.',
            target: '#channelBrowser',
            placement: 'center',
            advance: { type: 'next-button' },
            onNext: 'navigate:nickjfuentes',
          },
          {
            id: 'click-latest',
            title: 'Click the latest video',
            body: 'Click the top video tile in the channel grid (his most recent upload). The browser will open it.',
            target: '#channelBrowser',
            placement: 'center',
            advance: { type: 'webview-nav-to-video' },
          },
          {
            id: 'open-edit-menu',
            title: 'Open the Edit menu',
            body: 'Click <b>Edit</b> in the top menu bar to expose the URL field where we paste the video URL.',
            target: '.menu-item[data-menu="edit"]',
            placement: 'bottom',
            advance: { type: 'menu-open', menu: 'edit' },
          },
          {
            id: 'url-bar',
            title: 'The URL field',
            body: 'We have already pasted the current Rumble URL here. Hit <b>Load</b> to extract the stream and start the player.',
            target: '#urlIn',
            placement: 'bottom',
            advance: { type: 'click', target: '#loadBtn' },
            onEnter: 'paste-current-rumble-url',
          },
        ],
      },
      {
        id: 'basic-clipping',
        title: 'Basic Clipping',
        blurb: 'Mark IN/OUT points and export your first clip.',
        prereq: 'stream-loaded',
        steps: [
          {
            id: 'player',
            title: 'The player',
            body: 'This is the player. <kbd>Space</kbd> plays/pauses, drag the timeline to scrub.',
            target: '#playerWrap',
            placement: 'right',
            advance: { type: 'next-button' },
          },
          {
            id: 'mark-in',
            title: 'Mark IN',
            body: 'Find a moment you want to clip, then press <kbd>I</kbd> (or click the IN button) to mark the start.',
            target: '#markInBtn',
            placement: 'top',
            advance: { type: 'event', event: 'tutorial:markedIn' },
          },
          {
            id: 'mark-out',
            title: 'Mark OUT',
            body: 'Let it play a bit, then press <kbd>O</kbd> (or click OUT) to mark the end.',
            target: '#markOutBtn',
            placement: 'top',
            advance: { type: 'event', event: 'tutorial:markedOut' },
          },
          {
            id: 'clips-queue',
            title: 'Clips Queue',
            body: 'Your new clip lands here in the <b>Pending</b> list.',
            target: '#hubSection',
            placement: 'left',
            advance: { type: 'next-button' },
          },
          {
            id: 'caption-and-download',
            title: 'Caption and download',
            body: 'Each pending clip has a caption box and a Download button. Type a caption, then click Download to process the clip.',
            target: '#pendingClipList',
            placement: 'left',
            advance: { type: 'next-button' },
          },
          {
            id: 'output-folder',
            title: 'Where clips go',
            body: 'Finished clips appear in <b>Done</b>. Click the folder icon to open the output directory in Explorer.',
            target: '#openCompletedFolder',
            placement: 'left',
            advance: { type: 'next-button' },
          },
        ],
      },
      {
        id: 'watermarks',
        title: 'Watermarks & Preview',
        blurb: 'Stamp text or an image onto every clip, and preview the result.',
        prereq: 'pending-clip',
        steps: [
          {
            id: 'open-settings',
            title: 'Open Settings',
            body: 'Click <b>File &rarr; Settings</b> to open app settings.',
            target: '#ddSettings',
            placement: 'bottom',
            advance: { type: 'event', event: 'tutorial:settingsOpen' },
          },
          {
            id: 'assets-tab',
            title: 'Assets tab',
            body: 'Switch to the <b>Assets</b> tab &mdash; that is where universal watermark and outro live.',
            target: '.settings-tab[data-tab="assets"]',
            placement: 'right',
            advance: { type: 'click', target: '.settings-tab[data-tab="assets"]' },
          },
          {
            id: 'enable-watermark',
            title: 'Enable universal watermark',
            body: 'Toggle this on to apply a watermark to every clip you export.',
            target: '#cfgWatermark',
            placement: 'right',
            advance: { type: 'next-button' },
          },
          {
            id: 'configure-watermark',
            title: 'Configure the watermark',
            body: 'Click <b>Edit Watermark</b> to set the text or image and choose its position.',
            target: '#cfgEditWatermark',
            placement: 'right',
            advance: { type: 'next-button' },
          },
          {
            id: 'close-settings',
            title: 'Close settings to preview',
            body: 'Close settings &mdash; we will preview the watermark on the pending clip you made earlier.',
            target: '.modal-close',
            placement: 'left',
            advance: { type: 'event', event: 'tutorial:settingsClose' },
          },
          {
            id: 'preview-clip',
            title: 'Preview with image grab',
            body: 'On a pending clip, the <b>Preview</b> button grabs a frame and shows the watermark on top so you can check placement.',
            target: '[data-action="preview"]',
            placement: 'left',
            advance: { type: 'next-button' },
          },
          {
            id: 'per-clip-watermark',
            title: 'Per-clip override',
            body: 'The <b>Watermark</b> button on a clip card overrides the universal setting just for that clip.',
            target: '[data-action="watermark"]',
            placement: 'left',
            advance: { type: 'next-button' },
          },
        ],
      },
      {
        id: 'outros',
        title: 'Outros',
        blurb: 'Append a clip-ending video or image to every export.',
        steps: [
          {
            id: 'open-settings-outro',
            title: 'Open Settings &rarr; Assets',
            body: 'Open <b>File &rarr; Settings</b> and switch to the <b>Assets</b> tab.',
            target: '#ddSettings',
            placement: 'bottom',
            advance: { type: 'event', event: 'tutorial:assetsTabOpen' },
          },
          {
            id: 'enable-outro',
            title: 'Enable universal outro',
            body: 'Toggle this on to append the same outro file to every clip.',
            target: '#cfgOutroEnabled',
            placement: 'right',
            advance: { type: 'next-button' },
          },
          {
            id: 'browse-outro',
            title: 'Pick the outro file',
            body: 'Click <b>Browse</b> to choose a video or image. Recommended: short 2&ndash;4s file matching your clip resolution.',
            target: '#cfgOutroBrowse',
            placement: 'right',
            advance: { type: 'next-button' },
          },
          {
            id: 'per-clip-outro',
            title: 'Per-clip override',
            body: 'The <b>Outro</b> button on a clip card lets you swap or disable the outro for one clip.',
            target: '[data-action="outro"]',
            placement: 'left',
            advance: { type: 'next-button' },
          },
        ],
      },
      {
        id: 'encoding',
        title: 'FFmpeg & Output',
        blurb: 'Tune codec, quality, and where files land.',
        steps: [
          {
            id: 'open-settings-enc',
            title: 'Open Settings &rarr; Encoding',
            body: 'Open <b>File &rarr; Settings</b>, then switch to the <b>Encoding</b> tab.',
            target: '#ddSettings',
            placement: 'bottom',
            advance: { type: 'event', event: 'tutorial:encodingTabOpen' },
          },
          {
            id: 'video-codec',
            title: 'Video codec',
            body: 'h264 = max compatibility (X / YouTube safe). h265 = smaller files, narrower playback support. AV1 = best quality/size, slowest encode.',
            target: '#cfgVideoCodec',
            placement: 'right',
            advance: { type: 'next-button' },
          },
          {
            id: 'preset',
            title: 'Preset',
            body: 'Speed/size tradeoff. <b>fast</b> for long batches, <b>medium</b> default, <b>slow</b> for archive-quality.',
            target: '#cfgPreset',
            placement: 'right',
            advance: { type: 'next-button' },
          },
          {
            id: 'crf',
            title: 'CRF',
            body: 'Quality target. Lower = better/larger. <b>18</b> visually lossless, <b>23</b> default, <b>28</b> small files. Range 0&ndash;51.',
            target: '#cfgCrf',
            placement: 'right',
            advance: { type: 'next-button' },
          },
          {
            id: 'audio',
            title: 'Audio',
            body: 'AAC + 192k is the safe default. Bump bitrate up to 320k if you need pristine audio.',
            target: '#cfgAudioCodec',
            placement: 'right',
            advance: { type: 'next-button' },
          },
          {
            id: 'hwaccel',
            title: 'Hardware acceleration',
            body: 'If you have an NVIDIA / AMD / Intel GPU, enabling hwaccel speeds encoding 3&ndash;10x. Falls back to CPU automatically.',
            target: '#cfgHwaccel',
            placement: 'right',
            advance: { type: 'next-button' },
          },
          {
            id: 'output-dir',
            title: 'Output folder',
            body: 'Click the path at the bottom of the Clips Queue to change where clips are saved.',
            target: '#outputPath',
            placement: 'top',
            advance: { type: 'next-button' },
          },
          {
            id: 'save-encoding',
            title: 'Save and you are done',
            body: 'Click <b>Save</b> in the settings dialog and the new encoder settings apply to the next clip.',
            target: '.settings-save',
            placement: 'left',
            advance: { type: 'next-button' },
          },
        ],
      },
    ],
  };

  if (typeof module !== 'undefined' && module.exports) module.exports = content;
  if (typeof window !== 'undefined') window._tutorialContent = content;
})();
